# This is a basic workflow to help you get started with Actions

name: test the internet heroku

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Install requirements
        run: pip install -r requirements.txt
        
      - name: Check software versions
        run: |
          python --version
          pytest -V

      - name: Run the internet heroku app
        run: |
          docker run -d -p 7080:5000 --name internetapp gprestes/the-internet "curl www.google.com"
        
      - name: Get docker details
        run: docker container ls
        
      - name: curl the url
        run: curl localhost:7080/abtest
        
      - name: test the internet heroku
        run: pytest -v test_reqres_apis.py::test_docker
